# .readthedocs.yaml
# Read the Docs configuration file

version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - htmlzip
  - pdf

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
